### ISSUE TITLE
A bit more info about the mod

### ISSUE THREAD

**Issue by pikachukaki** [Jimmyokok/CustomVehiclePathfind#1]
I think we need a bit more info about cfg of the mod and what exacly to expect so we can understand if the mod is working and how! 
Thanks

**Comment by Jimmyokok** [comment]
The thing is, I haven't figured out how to update mod description on thunderstore.io. Readme of this repository will get updated.

**Comment by Jimmyokok** [comment]
> I think we need a bit more info about cfg of the mod and what exacly to expect so we can understand if the mod is working and how! Thanks

The readme has been updated.

**Comment by pikachukaki** [comment]
Thanks just to be a pain if you can if it's possible to have the cfg preconfig with values you think works best.
Also if this isn't possible can you please add the range of the values? 0-10 or 0 - 10.000!
Thanks

**Comment by Jimmyokok** [comment]
I don't believe that there is a "best" config setting, but:

- For the driving cost, the game default value is 0.01. I find under 1.0, the traffic flow of my super dense city dropped by around 30% .
- For the lane changing cost, the game default value is 2. I don't use this function in my own city, and I didn't see any observable improvement on traffic when the cost is set to 5 or 10. However, when I set it to 10000, the traffic just weirdly collapsed, as if nobody wants to drive cars any more.
- For the unsafe behavior cost, the game default value is 50/100. I find setting this cost to high values extremely helpful. After setting it to 1000, no vehicles ever break traffic rules.

**Comment by valenntinoo** [comment]
Hey, any chance that this mod would become compatible with BepInEx 6?

**Comment by Jimmyokok** [comment]
> [valenntinoo](/valenntinoo)

I have uploaded a BIE6 version in release.

**Comment by valenntinoo** [comment]
wow, thank you so much
