### ISSUE TITLE
Broke by 1.0.19f1 patch

### ISSUE THREAD

**Issue by GIS-PuppetMaster** [Jimmyokok/CustomVehiclePathfind#4]
Any schedule to fix it?

**Comment by Jimmyokok** [comment]
I tested it, and it worked perfectly on 1.0.19f1, with only this mod enabled.
If error indeed occurs, please provide more information.

**Comment by GIS-PuppetMaster** [comment]
> I tested it, and it worked perfectly on 1.0.19f1, with only this mod enabled.我测试了它，它在 1.0.19f1 上运行得很好，只启用了这个 mod。 If error indeed occurs, please provide more information. 如果确实发生错误，请提供更多信息。

Yes, I made a mistake, it's other mod's problem
