### ISSUE TITLE
Lane changing punishment

### ISSUE THREAD

**Issue by valenntinoo** [Jimmyokok/CustomVehiclePathfind#5]
Hi, this mod is great. I have a question about the lane changing punishment feature. I feel like people don't like to change lanes by default in this game. They do it as little as possible and often very late. If I would set the lane punishment value lower, do you think it could stimulate changing lanes instead of punishing? If so, what values would i have to try?

**Comment by Jimmyokok** [comment]
I have no experience in tuning the lane changing punishment value, so I can't give you a "recommended" setting that fulfills your need. For reference, the default value in vanilla is 2, which means any value below 2 would theoretically encourage lane changing behaviors.

**Comment by valenntinoo** [comment]
The vanilla value is exactly what I was looking for, i'll try and see if values below 2 have any effect. Thanks a lot!
